data_dir: 'C:/Users/made2928/OneDrive/Documents/MISU/AeroGP/training_data_withzero/'
test_str: ''
log_dir: 'C:/Users/made2928/OneDrive/Documents/MISU/AeroGP/logs/zeroZinit_test/'
external_test: 'C:/Users/made2928/OneDrive/Documents/MISU/AeroGP/testing_data/inputs_af_OCx2.nc'
opt: True

# ------
# Training data with one experiment with zero input and zero output values included.
#
# data_dir: where the training data is stored for the model
# test_str: experiment held out for testing during model training (found in the data_dir)
# log_dir: where the checkpoints for the trained model are stored, and where the output from testing is saved
# external_test: this is an optional input, if the model is to be tested on a different dataset than test_str
# opt: if True, the model is trained. If False, the model is loaded from the last checkpoint and tested on test_str or external_test

# to run, type in the command line:
# python AeroGP_SVGP_train_model.py ./config_files/X_config3.yml
# ------