data_dir: 'C:/Users/made2928/OneDrive/Documents/MISU/NorESMem/training_data_v2/'
test_str: 'ramip_ea'
log_dir: 'C:/Users/made2928/OneDrive/Documents/MISU/NorESMem/logs/lr_1lin/RAMIP EA'
#external_test: 'C:/Users/made2928/OneDrive/Documents/MISU/NorESMem/testing_data/inputs_ramipEA2.nc'
opt: True

# ------
# Testing. Less regions (dropping S.A. and Aus) seems to have recovered the fit.
# ------
